import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import Banner from '@public/banner.jpg'
import { Header } from '@/components/header/header'
import { Card } from '@/components/card/card'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <Header />

            <main className={styles.container}>
                <section>
                    <h1 className={styles.title}>
                        Todas as músicas católicas reunidas para você tocar!
                    </h1>

                    <Image src={Banner} alt='' priority />
                </section>

                <section>
                    <Card />
                </section>
            </main>
        </>
    )
}
